name: Docker Image Build & Push

on: 
  push:
    branches:
      - main  # Runs when you push to 'main' branch

jobs:
  build:
    runs-on: ubuntu-latest  # Use Ubuntu as the runner

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        run: echo ${{ secrets.DOCKERTOKEN }} | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and Push Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/fastapi-app:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/fastapi-app:latest
